/**
 * Satu-satunya pintu masuk ikon di situs ini.
 * Wajib Phosphor (@phosphor-icons/react). Default weight `regular`;
 * `bold` hanya untuk ikon checklist kecil dan toggle navigasi
 * (agar terbaca di ukuran kecil). `fill` hanya untuk status
 * aktif/terpilih. Tanpa duotone.
 * Entry SSR agar aman dirender di Server Component.
 */
export {
  AppleLogo,
  GooglePlayLogo,
  DownloadSimple,
  ShieldCheck,
  SealCheck,
  Heart,
  HeartStraight,
  ChatCircleDots,
  ChatCircle,
  ShareNetwork,
  Bell,
  BellRinging,
  Check,
  CheckCircle,
  X,
  XCircle,
  Plus,
  Minus,
  ArrowRight,
  ArrowDown,
  ArrowLeft,
  ArrowUpRight,
  CaretDown,
  CaretRight,
  Package,
  Truck,
  Bank,
  Storefront,
  MagnifyingGlass,
  House,
  User,
  UserCircleCheck,
  Users,
  List,
  Globe,
  Envelope,
  Phone,
  MapPin,
  Briefcase,
  Newspaper,
  Lock,
  CreditCard,
  Handshake,
  Receipt,
  CurrencyCircleDollar,
  Timer,
  Eye,
  EyeSlash,
  Warning,
  WarningCircle,
  Info,
  Question,
  CheckSquare,
  Square,
  Star,
  ThumbsUp,
  Camera,
  Image,
  PaperPlaneTilt,
  DotsThree,
  MagnifyingGlassPlus,
  Funnel,
  Tag,
  Wallet,
  ArrowsLeftRight,
  CircleNotch,
  ShoppingBag,
  Headphones,
  DeviceMobile,
} from "@phosphor-icons/react/dist/ssr";
